name: Test action

on:
  push:
  pull_request:

jobs:
  calculate-age:
    runs-on: ubuntu-latest
    steps:
      - uses: frdmn/age-calculator-action@main
        id: birthday
        with:
          date: '1997-10-27'
      - run: |
          echo "Authors age in years: ${{ steps.birthday.outputs.age }}"
